import React, { useEffect, useState } from 'react';
import { Platform, ScrollView, StyleSheet, Text, View } from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { WebView } from 'react-native-webview';
import { Button, Card, Field, Label } from '../../components/UI'; import { cameraUrl, checkLocalDevice, subscribeToLocalDetections, type LocalConfig } from '../../repositories/localDevice'; import { colors } from '../../theme';
const DEFAULT: LocalConfig = { hostname: 'aipms1234.local', webUiPort: 7000, cameraPort: 4912, cameraPath: '/embed' };
export default function CameraScreen() { const [config, setConfig] = useState(DEFAULT); const [state, setState] = useState<'idle' | 'connecting' | 'connected' | 'unavailable'>('idle'); const [message, setMessage] = useState('Connect your phone to the same Wi-Fi as the AIPMS unit.'); const [detection, setDetection] = useState<{ content: string; confidence: number; timestamp?: string } | null>(null); useEffect(() => { AsyncStorage.getItem('aipms-local-config').then(value => { if (value) setConfig(JSON.parse(value)); }); }, []); useEffect(() => { if (state !== 'connected') return; return subscribeToLocalDetections(config, setDetection); }, [state, config]); async function connect() { setState('connecting'); setMessage('Searching the farm network…'); try { const ok = await checkLocalDevice(config); if (!ok) throw new Error(); await AsyncStorage.setItem('aipms-local-config', JSON.stringify(config)); setState('connected'); setMessage('Local device connected. The video remains on this network.'); } catch { setState('unavailable'); setMessage('The unit could not be reached. Check the Wi-Fi and local address, then retry.'); } } return <ScrollView style={s.page} contentContainerStyle={s.content}><View style={s.head}><Label>Local network only</Label><Text style={s.title}>Farm camera</Text><Text style={s.copy}>The continuous feed goes directly from the UNO Q to this device. It is never uploaded to Supabase.</Text></View><View style={s.stage}>{state === 'connected' ? <CameraFrame uri={cameraUrl(config)} /> : <><Text style={s.cameraIcon}>▣</Text><Text style={s.stageTitle}>{state === 'connecting' ? 'Connecting…' : state === 'unavailable' ? 'Camera unavailable' : 'Camera not connected'}</Text></>}<Text style={[s.status, state === 'connected' && s.live]}>{state === 'connected' ? 'LIVE' : state.toUpperCase()}</Text></View><Card><Text style={s.message}>{message}</Text><Field label="Local hostname or LAN IP" value={config.hostname} onChangeText={hostname => setConfig(old => ({ ...old, hostname }))} autoCapitalize="none" autoCorrect={false} /><View style={{ marginTop: 15 }}><Button title={state === 'connecting' ? 'Searching…' : 'Connect to camera'} loading={state === 'connecting'} onPress={connect} /></View></Card><Label>Latest rat or snake detection</Label><Card>{detection ? <><Text style={s.detect}>{detection.content}</Text><Text style={s.confidence}>{Math.round(detection.confidence * 100)}% confidence · {detection.timestamp ? new Date(detection.timestamp).toLocaleTimeString() : 'just now'}</Text></> : <Text style={s.copy}>No relevant local detection received during this connection.</Text>}</Card></ScrollView>; }
function CameraFrame({ uri }: { uri: string }) { if (Platform.OS === 'web') return React.createElement('iframe' as never, { src: uri, title: 'AIPMS local camera', style: { width: '100%', height: '100%', border: 0 } }); return <WebView source={{ uri }} style={{ flex: 1, width: '100%' }} allowsInlineMediaPlayback />; }
const s = StyleSheet.create({ page: { flex: 1, backgroundColor: colors.sage }, content: { padding: 18, gap: 14, paddingBottom: 30, maxWidth: 760, width: '100%', alignSelf: 'center' }, head: { marginTop: 26 }, title: { fontSize: 30, fontWeight: '900', color: colors.barn, marginTop: 5 }, copy: { color: colors.barnSoft, lineHeight: 20, marginTop: 7 }, stage: { height: 250, borderRadius: 22, overflow: 'hidden', backgroundColor: colors.barn, alignItems: 'center', justifyContent: 'center' }, cameraIcon: { color: colors.amber, fontSize: 38 }, stageTitle: { color: colors.paper, marginTop: 10, fontWeight: '800' }, status: { position: 'absolute', right: 12, top: 12, color: '#FFFFFF88', backgroundColor: '#FFFFFF16', borderRadius: 99, paddingHorizontal: 9, paddingVertical: 5, fontSize: 9, fontWeight: '900' }, live: { color: '#BDEBC4', backgroundColor: '#4C7A5744' }, message: { color: colors.barnSoft, lineHeight: 19, marginBottom: 16 }, detect: { color: colors.bad, fontSize: 28, fontWeight: '900', textTransform: 'capitalize' }, confidence: { color: colors.barnSoft, marginTop: 6 } });
