import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { Card, Label } from '../../components/UI';
import { useAuth } from '../../context/AuthContext';
import { latestReading, subscribeToReadings } from '../../repositories/cloud';
import { colors } from '../../theme';
import type { Reading } from '../../types';

export default function Home() {
  const { user, device } = useAuth();
  const [reading, setReading] = useState<Reading | null>(null);
  const [busy, setBusy] = useState(true);
  const [checkedAt, setCheckedAt] = useState(() => Date.now());
  const [error, setError] = useState('');
  const load = useCallback(async () => {
    if (!device) return;
    setError('');
    try { setReading(await latestReading(device.id)); setCheckedAt(Date.now()); }
    catch (e) { setError(e instanceof Error ? e.message : 'Unable to load readings.'); }
    finally { setBusy(false); }
  }, [device]);
  useEffect(() => { load(); if (device) return subscribeToReadings(device.id, value => { setReading(value); setCheckedAt(Date.now()); }); }, [device, load]);
  const stale = !reading || checkedAt - new Date(reading.created_at).getTime() > 120000;
  if (busy) return <View style={s.center}><ActivityIndicator color={colors.barn} /></View>;

  return <ScrollView style={s.page} contentContainerStyle={s.content} refreshControl={<RefreshControl refreshing={busy} onRefresh={load} />}>
    <View style={s.header}><View><Label>Farm overview</Label><Text style={s.title}>Hello, {user?.user_metadata?.full_name?.split(' ')[0] || 'Farmer'}</Text></View><View style={[s.connection, stale && s.offline]}><View style={[s.dot, stale && { backgroundColor: '#999' }]} /><Text style={s.connectionText}>{stale ? 'STALE' : 'LIVE'}</Text></View></View>
    {error ? <Text style={s.error}>{error}</Text> : null}
    <Card dark><View style={s.between}><View><Label light>{device?.name || 'AIPMS unit'}</Label><Text style={s.deviceId}>{device?.id}</Text></View><Ionicons name="hardware-chip-outline" size={28} color={colors.amber} /></View><Text style={s.updated}>{reading ? `Updated ${new Date(reading.created_at).toLocaleTimeString()}` : 'Waiting for the first sensor reading'}</Text></Card>
    <View style={s.metrics}><Metric title="Temperature" value={reading?.temperature} unit="°C" bad={reading?.temperature_high || reading?.temperature_low} icon="thermometer-outline" /><Metric title="Humidity" value={reading?.humidity} unit="%" bad={reading?.humidity_high || reading?.humidity_low} icon="water-outline" /><Metric title="Ammonia / air" value={reading?.air_quality} unit=" ppm" bad={reading?.air_quality_bad} icon="cloud-outline" wide /></View>
    <Card><View style={s.between}><View><Label>Automatic equipment</Label><Text style={s.sectionTitle}>Current state</Text></View><Text style={s.auto}>AUTOMATIC</Text></View><State label="Ventilation fan" on={reading?.fan_on} reason={reading?.temperature_high ? 'High temperature' : reading?.air_quality_bad ? 'Poor air quality' : undefined} /><State label="Humidifier" on={reading?.humidifier_on} reason={reading?.humidity_low ? 'Low humidity' : undefined} /><State label="Hardware alarm" on={reading?.alarm_active} alarm /></Card>
    <Card><Label>Condition flags</Label><Text style={s.sectionTitle}>Environmental status</Text><Flag label="Temperature high" active={reading?.temperature_high} /><Flag label="Temperature low" active={reading?.temperature_low} /><Flag label="Humidity high" active={reading?.humidity_high} /><Flag label="Humidity low" active={reading?.humidity_low} /><Flag label="Ammonia / air quality bad" active={reading?.air_quality_bad} /></Card>
    <Card dark><View style={s.between}><View><Label light>AI threat monitor</Label><Text style={s.cameraTitle}>Camera & detection</Text></View><Text style={[s.cameraState, reading?.camera_live === true && s.cameraLive]}>{reading?.camera_live === true ? 'LIVE' : reading?.camera_live === false ? 'OFFLINE' : 'STATUS UNAVAILABLE'}</Text></View><View style={s.detectionBox}><Text style={s.detectionLabel}>LATEST RAT OR SNAKE DETECTION</Text><Text style={[s.detectionValue, reading?.detection_label && { color: '#F3A88F' }]}>{reading?.detection_label || 'None'}</Text>{reading?.detection_label ? <Text style={s.detectionMeta}>{Math.round((reading.detection_confidence || 0) * 100)}% confidence · {new Date(reading.detection_at || reading.created_at).toLocaleString()}</Text> : <Text style={s.detectionMeta}>No relevant detection reported</Text>}</View><Text style={s.cloudNote}>Only camera status and rat/snake results use the cloud. Video remains on the farm network.</Text></Card>
  </ScrollView>;
}

function Metric({ title, value, unit, bad, icon, wide }: { title: string; value?: number | null; unit: string; bad?: boolean; icon: keyof typeof Ionicons.glyphMap; wide?: boolean }) { return <View style={[s.metric, wide && s.wide, bad && s.metricBad]}><Ionicons name={icon} size={20} color={bad ? colors.bad : colors.good} /><Text style={s.metricLabel}>{title}</Text><Text style={s.metricValue}>{value == null ? '—' : value.toFixed(1)}<Text style={s.unit}>{value == null ? '' : unit}</Text></Text><Text style={[s.condition, bad && { color: colors.bad }]}>{value == null ? 'Waiting' : bad ? 'Attention' : 'Normal'}</Text></View>; }
function State({ label, on, reason, alarm }: { label: string; on?: boolean; reason?: string; alarm?: boolean }) { return <View style={s.row}><View><Text style={s.rowLabel}>{label}</Text><Text style={s.reason}>{reason || (on ? 'Active automatically' : 'No automatic action')}</Text></View><Text style={[s.badge, on && (alarm ? s.badgeBad : s.badgeOn)]}>{on ? (alarm ? 'ALARM' : 'RUNNING') : 'OFF'}</Text></View>; }
function Flag({ label, active }: { label: string; active?: boolean }) { return <View style={s.row}><Text style={s.rowLabel}>{label}</Text><Text style={[s.flag, active && s.flagActive]}>{active ? 'ACTIVE' : 'NORMAL'}</Text></View>; }

const s = StyleSheet.create({ page:{flex:1,backgroundColor:colors.sage},content:{padding:18,gap:14,paddingBottom:30,maxWidth:900,width:'100%',alignSelf:'center'},center:{flex:1,justifyContent:'center',alignItems:'center',backgroundColor:colors.sage},header:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginTop:26},title:{fontSize:30,fontWeight:'900',color:colors.barn,marginTop:5},connection:{flexDirection:'row',gap:6,alignItems:'center',backgroundColor:'#DDECDD',paddingHorizontal:10,paddingVertical:6,borderRadius:99},offline:{backgroundColor:'#E6E6E2'},dot:{width:7,height:7,borderRadius:7,backgroundColor:colors.good},connectionText:{fontSize:10,fontWeight:'900',color:colors.barn},error:{color:colors.bad},between:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},deviceId:{color:colors.paper,fontSize:24,fontWeight:'900',marginTop:6},updated:{color:'#FFFFFF88',marginTop:18,fontSize:12},metrics:{flexDirection:'row',flexWrap:'wrap',gap:10},metric:{minWidth:'47%',flexGrow:1,backgroundColor:colors.paper,borderWidth:1,borderColor:colors.line,borderRadius:18,padding:16},wide:{minWidth:'100%'},metricBad:{backgroundColor:'#FCEDE8',borderColor:'#E9B5A5'},metricLabel:{color:colors.barnSoft,fontSize:12,marginTop:12},metricValue:{color:colors.barn,fontWeight:'900',fontSize:29,marginTop:3},unit:{fontSize:14},condition:{color:colors.good,fontWeight:'800',fontSize:11,marginTop:5},sectionTitle:{fontSize:20,fontWeight:'900',color:colors.barn,marginTop:4},auto:{color:colors.good,backgroundColor:colors.sage,padding:7,borderRadius:99,fontSize:9,fontWeight:'900'},row:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',paddingVertical:13,borderBottomWidth:1,borderBottomColor:colors.line},rowLabel:{color:colors.barn,fontWeight:'800'},reason:{color:colors.barnSoft,fontSize:11,marginTop:3},badge:{color:colors.barnSoft,backgroundColor:'#ECEDEA',fontWeight:'900',fontSize:10,padding:7,borderRadius:99},badgeOn:{color:colors.good,backgroundColor:'#E3EFE4'},badgeBad:{color:colors.bad,backgroundColor:'#F9E1DA'},flag:{color:colors.good,backgroundColor:'#E3EFE4',fontWeight:'900',fontSize:9,paddingHorizontal:9,paddingVertical:6,borderRadius:99},flagActive:{color:colors.bad,backgroundColor:'#F9E1DA'},cameraTitle:{color:colors.paper,fontSize:20,fontWeight:'900',marginTop:4},cameraState:{color:'#FFFFFF77',backgroundColor:'#FFFFFF12',borderRadius:99,paddingHorizontal:10,paddingVertical:6,fontSize:9,fontWeight:'900'},cameraLive:{color:'#BDEBC4',backgroundColor:'#4C7A5744'},detectionBox:{marginTop:18,borderWidth:1,borderColor:'#FFFFFF18',borderRadius:14,padding:15},detectionLabel:{color:'#FFFFFF77',fontSize:9,letterSpacing:1,fontWeight:'900'},detectionValue:{color:'#FFFFFF99',fontSize:26,fontWeight:'900',textTransform:'capitalize',marginTop:8},detectionMeta:{color:'#FFFFFF88',fontSize:11,marginTop:6},cloudNote:{color:'#FFFFFF77',fontSize:11,lineHeight:16,marginTop:14} });
