-- Safe to run more than once in the Supabase SQL editor.
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null,
  full_name text,
  created_at timestamptz not null default now()
);

create table if not exists public.devices (
  id text primary key,
  owner_user_id uuid references auth.users(id) on delete set null,
  name text not null,
  local_hostname text,
  claimed_at timestamptz,
  status text not null default 'offline',
  last_seen_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.sensor_readings (
  id bigint generated by default as identity primary key,
  device_id text not null references public.devices(id) on delete cascade,
  temperature double precision,
  humidity double precision,
  air_quality double precision,
  fan_on boolean not null default false,
  humidifier_on boolean not null default false,
  alarm_active boolean not null default false,
  temperature_high boolean not null default false,
  temperature_low boolean not null default false,
  humidity_high boolean not null default false,
  humidity_low boolean not null default false,
  air_quality_bad boolean not null default false,
  camera_live boolean,
  detection_label text,
  detection_confidence double precision,
  detection_at timestamptz,
  created_at timestamptz not null default now()
);

-- CREATE TABLE IF NOT EXISTS does not update tables created by an older
-- schema. Add fields required by the web app when those tables already exist.
alter table public.profiles
  add column if not exists full_name text,
  add column if not exists created_at timestamptz not null default now();

alter table public.devices
  add column if not exists owner_user_id uuid references auth.users(id) on delete set null;

alter table public.devices
  alter column owner_user_id drop not null,
  add column if not exists name text not null default 'Poultry house',
  add column if not exists local_hostname text,
  add column if not exists claimed_at timestamptz,
  add column if not exists status text not null default 'offline',
  add column if not exists last_seen_at timestamptz,
  add column if not exists created_at timestamptz not null default now();

alter table public.sensor_readings
  add column if not exists fan_on boolean not null default false,
  add column if not exists humidifier_on boolean not null default false,
  add column if not exists alarm_active boolean not null default false,
  add column if not exists temperature_high boolean not null default false,
  add column if not exists temperature_low boolean not null default false,
  add column if not exists humidity_high boolean not null default false,
  add column if not exists humidity_low boolean not null default false,
  add column if not exists air_quality_bad boolean not null default false,
  add column if not exists camera_live boolean,
  add column if not exists detection_label text,
  add column if not exists detection_confidence double precision,
  add column if not exists detection_at timestamptz,
  add column if not exists created_at timestamptz not null default now();

alter table public.sensor_readings
  alter column camera_live drop not null,
  alter column camera_live drop default;

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'sensor_readings_detection_label_check') then
    alter table public.sensor_readings
      add constraint sensor_readings_detection_label_check
      check (detection_label is null or lower(detection_label) in ('rat', 'snake'));
  end if;

  if not exists (select 1 from pg_constraint where conname = 'sensor_readings_detection_confidence_check') then
    alter table public.sensor_readings
      add constraint sensor_readings_detection_confidence_check
      check (detection_confidence is null or detection_confidence between 0 and 1);
  end if;
end;
$$;

create table if not exists public.daily_records (
  id uuid primary key default gen_random_uuid(),
  device_id text not null references public.devices(id) on delete cascade,
  owner_user_id uuid not null references auth.users(id) on delete cascade,
  record_date date not null,
  chicks_hatched integer not null default 0 check (chicks_hatched >= 0),
  birds_bred integer not null default 0 check (birds_bred >= 0),
  eggs_collected integer not null default 0 check (eggs_collected >= 0),
  mortality_count integer not null default 0 check (mortality_count >= 0),
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (device_id, record_date)
);

-- Bring daily_records created by an older schema up to the current contract.
-- owner_user_id remains nullable for legacy rows; every new app write supplies it.
alter table public.daily_records
  add column if not exists owner_user_id uuid references auth.users(id) on delete cascade,
  add column if not exists chicks_hatched integer not null default 0,
  add column if not exists birds_bred integer not null default 0,
  add column if not exists eggs_collected integer not null default 0,
  add column if not exists mortality_count integer not null default 0,
  add column if not exists note text,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

create table if not exists public.alerts (
  id bigint generated by default as identity primary key,
  device_id text not null references public.devices(id) on delete cascade,
  type text not null check (type in ('temp_high','temp_low','humidity_high','humidity_low','air_bad','device_offline')),
  severity text not null check (severity in ('warning','critical')),
  started_at timestamptz not null default now(),
  resolved_at timestamptz,
  read_at timestamptz,
  message text not null
);

create unique index if not exists alerts_one_active_type_idx on public.alerts(device_id, type) where resolved_at is null;
create index if not exists daily_records_device_date_idx on public.daily_records(device_id, record_date desc);
create index if not exists alerts_device_started_idx on public.alerts(device_id, started_at desc);

create index if not exists sensor_readings_device_time_idx on public.sensor_readings(device_id, created_at desc);
alter table public.profiles enable row level security;
alter table public.devices enable row level security;
alter table public.sensor_readings enable row level security;
alter table public.daily_records enable row level security;
alter table public.alerts enable row level security;

drop policy if exists "profiles_select_own" on public.profiles;
drop policy if exists "profiles_update_own" on public.profiles;
drop policy if exists "devices_owner_access" on public.devices;
drop policy if exists "readings_owner_select" on public.sensor_readings;
drop policy if exists "records_owner_access" on public.daily_records;
drop policy if exists "alerts_owner_select" on public.alerts;
drop policy if exists "alerts_owner_update" on public.alerts;

create policy "profiles_select_own" on public.profiles for select using (id = auth.uid());
create policy "profiles_update_own" on public.profiles for update using (id = auth.uid());
create policy "devices_owner_access" on public.devices for all using (owner_user_id = auth.uid()) with check (owner_user_id = auth.uid());
create policy "readings_owner_select" on public.sensor_readings for select using (exists (select 1 from public.devices d where d.id = device_id and d.owner_user_id = auth.uid()));
create policy "records_owner_access" on public.daily_records for all using (owner_user_id = auth.uid() and exists (select 1 from public.devices d where d.id = device_id and d.owner_user_id = auth.uid())) with check (owner_user_id = auth.uid() and exists (select 1 from public.devices d where d.id = device_id and d.owner_user_id = auth.uid()));
create policy "alerts_owner_select" on public.alerts for select using (exists (select 1 from public.devices d where d.id = device_id and d.owner_user_id = auth.uid()));
create policy "alerts_owner_update" on public.alerts for update using (exists (select 1 from public.devices d where d.id = device_id and d.owner_user_id = auth.uid()));

create or replace function public.claim_device(requested_device_id text, requested_name text default null)
returns public.devices
language plpgsql
security definer
set search_path = public
as $$
declare
  claimed public.devices;
  normalized_id text := upper(trim(requested_device_id));
begin
  if auth.uid() is null then raise exception 'Authentication required' using errcode = '42501'; end if;
  if normalized_id !~ '^AIPMS[A-Z0-9-]{3,}$' then raise exception 'Invalid device ID'; end if;
  if not exists (select 1 from public.devices where id = normalized_id) then raise exception 'Device not found'; end if;

  update public.devices
  set owner_user_id = auth.uid(),
      name = coalesce(nullif(trim(requested_name), ''), name),
      claimed_at = now()
  where id = normalized_id and owner_user_id is null
  returning * into claimed;

  if claimed.id is null then
    if exists (select 1 from public.devices where id = normalized_id and owner_user_id = auth.uid()) then
      select * into claimed from public.devices where id = normalized_id;
      return claimed;
    end if;
    raise exception 'Device is already registered to another account' using errcode = '23505';
  end if;
  return claimed;
end;
$$;

revoke all on function public.claim_device(text, text) from public;
grant execute on function public.claim_device(text, text) to authenticated;

-- Exposes only an availability boolean so the signup form can give useful
-- feedback without allowing anonymous users to list registered devices.
create or replace function public.is_device_available(candidate_id text)
returns boolean
language sql
security definer
set search_path = public
as $$
  select nullif(trim(candidate_id), '') is not null
    and exists (
      select 1 from public.devices
      where id = upper(trim(candidate_id)) and owner_user_id is null
    );
$$;

revoke all on function public.is_device_available(text) from public;
grant execute on function public.is_device_available(text) to anon, authenticated;

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, username, full_name) values (new.id, coalesce(nullif(new.raw_user_meta_data->>'username', ''), split_part(new.email, '@', 1)), nullif(new.raw_user_meta_data->>'full_name', ''));
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'sensor_readings'
  ) then
    alter publication supabase_realtime add table public.sensor_readings;
  end if;
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'alerts') then
    alter publication supabase_realtime add table public.alerts;
  end if;
end;
$$;
