import { PropsWithChildren, ReactNode } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Text, TextInput, TextInputProps, View } from 'react-native';
import { colors, radius } from '../theme';
export function Screen({ children }: PropsWithChildren) { return <View style={s.screen}>{children}</View>; }
export function Card({ children, dark = false }: PropsWithChildren<{ dark?: boolean }>) { return <View style={[s.card, dark && s.dark]}>{children}</View>; }
export function Label({ children, light = false }: PropsWithChildren<{ light?: boolean }>) { return <Text style={[s.label, light && { color: '#FFFFFF88' }]}>{children}</Text>; }
export function Button({ title, onPress, loading, secondary }: { title: string; onPress: () => void; loading?: boolean; secondary?: boolean }) { return <Pressable disabled={loading} onPress={onPress} style={[s.button, secondary && s.secondary]}>{loading ? <ActivityIndicator color={secondary ? colors.barn : colors.paper} /> : <Text style={[s.buttonText, secondary && { color: colors.barn }]}>{title}</Text>}</Pressable>; }
export function Field({ label, error, ...props }: TextInputProps & { label: string; error?: string }) { return <View style={{ gap: 7 }}><Text style={s.fieldLabel}>{label}</Text><TextInput placeholderTextColor="#7C887F" {...props} style={s.input} />{error ? <Text style={s.error}>{error}</Text> : null}</View>; }
export function Empty({ icon, title, copy, action }: { icon?: ReactNode; title: string; copy: string; action?: ReactNode }) { return <Card><View style={s.empty}>{icon}<Text style={s.emptyTitle}>{title}</Text><Text style={s.muted}>{copy}</Text>{action}</View></Card>; }
const s = StyleSheet.create({ screen: { flex: 1, backgroundColor: colors.paper }, card: { backgroundColor: colors.white, borderWidth: 1, borderColor: colors.line, borderRadius: radius.md, padding: 18 }, dark: { backgroundColor: colors.barn, borderColor: colors.barn }, label: { color: colors.barnSoft, fontSize: 11, letterSpacing: 1.2, fontWeight: '800', textTransform: 'uppercase' }, button: { minHeight: 50, borderRadius: radius.pill, backgroundColor: colors.barn, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 22 }, secondary: { backgroundColor: colors.sageDeep }, buttonText: { color: colors.paper, fontWeight: '800', fontSize: 15 }, fieldLabel: { color: colors.barn, fontWeight: '700', fontSize: 13 }, input: { minHeight: 50, borderRadius: radius.sm, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.white, color: colors.barn, paddingHorizontal: 14, fontSize: 16 }, error: { color: colors.bad, fontSize: 12 }, empty: { alignItems: 'center', gap: 8, paddingVertical: 14 }, emptyTitle: { fontSize: 18, fontWeight: '800', color: colors.barn }, muted: { color: colors.barnSoft, textAlign: 'center', lineHeight: 20 } });
export const ui = s;
